DeclareCategory("IsCObject",IsObject);

DeclareOperation("CohomologyGenerators", 
  [IsCObject,IsPosInt]);
DeclareOperation("CohomologyObject",
  [IsGroup,IsObject]);
DeclareOperation("CohomologyRelators", 
  [IsCObject,IsPosInt]);
DeclareOperation("CohomologyRing", 
  [IsCObject,IsPosInt]);
DeclareOperation("Inclusion",
  [IsGroup,IsGroup]);
DeclareOperation("IsHomogeneous",[IsSCAlgebraObj]);
DeclareOperation("ProjectiveResolution", 
  [IsCObject,IsPosInt]);
DeclareOperation("BoundaryMap",
  [IsCObject,IsInt]);

DeclareGlobalFunction("ChangeOfBasisMatrix");
DeclareGlobalFunction("ExtractColumn");
DeclareGlobalFunction("FirstLift");
DeclareGlobalFunction("FirstStep");
DeclareGlobalFunction("GeneratorsOfRadical");
DeclareGlobalFunction("DownTheMiddle");
DeclareGlobalFunction("InducedHomomorphismOnCohomology");
DeclareGlobalFunction("Intersperse");
DeclareGlobalFunction("MakeMultiplicationTable");
DeclareGlobalFunction("_MasseyProduct");
DeclareGlobalFunction("MasseyProduct");
DeclareGlobalFunction("LiftChainMap");
DeclareGlobalFunction("LiftChainMapMassey");
DeclareGlobalFunction("LiftHom");
DeclareGlobalFunction("LocateGeneratorsInCohomologyRing");
DeclareGlobalFunction("PCGens");
DeclareGlobalFunction("ProductOfChainMaps");
DeclareGlobalFunction("ReverseLex");
DeclareGlobalFunction("_RegularModule");
